version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: "Compile Tests"
          command: |
            mkdir build
            cd build
            cmake -DSLCAPI_COMPILE_TESTS=ON ..
            cmake --build .
      - run:
          name: "Run Unit Tests"
          command: |
            cd build
            ctest
