// Simulink CAPI - C++ header only library to interface with code generated by Simulink.
// Copyright (C) 2020-2021  Danish Belal
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License Version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License along
// with this program; if not, write to the Free Software Foundation, Inc.,
// 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

#ifndef _PARAMETER_HPP_
#define _PARAMETER_HPP_

#include <exception>
#include <functional>
#include <optional>
#include <sstream>
#include <string>
#include <type_traits>

#include "AccessorHelper.hpp"
#include "CapiError.hpp"
#include "ModelTraits.hpp"

#ifdef ENABLE_RUNTIME_TYPE_CHECKING
#include "cleantype.hpp"
#endif

namespace db::simulink
{

constexpr auto ENABLE_EXCEPTIONS = true;
constexpr auto DISABLE_EXCEPTIONS = false;

template <typename WrappedElement, typename ModelStruct, bool ExceptionsEnabled>
class CapiAccessor;

template <typename ModelStruct, bool ExceptionsEnabled = ENABLE_EXCEPTIONS>
using BlockParameters = CapiAccessor<rtwCAPI_BlockParameters, ModelStruct, ExceptionsEnabled>;
template <typename ModelStruct, bool ExceptionsEnabled = ENABLE_EXCEPTIONS>
using ModelParameters = CapiAccessor<rtwCAPI_ModelParameters, ModelStruct, ExceptionsEnabled>;
template <typename ModelStruct, bool ExceptionsEnabled = ENABLE_EXCEPTIONS>
using States = CapiAccessor<rtwCAPI_States, ModelStruct, ExceptionsEnabled>;
template <typename ModelStruct, bool ExceptionsEnabled = ENABLE_EXCEPTIONS>
using Signals = CapiAccessor<rtwCAPI_Signals, ModelStruct, ExceptionsEnabled>;

template <typename WrappedElement, typename ModelStruct, bool ExceptionsEnabled>
class CapiAccessor
{
    static_assert(has_datamapinfo_v<ModelStruct>,
        "The Model Structure needs to have a DataMapInfo Member."
        "If it doesnt have one, its either not a Model Structure, "
        "or you didnt enable the C API.");

    ModelStruct& mMS;
    CapiError mError;

public:
    CapiAccessor(ModelStruct& MS);

    /// Returns a reference to the element.
    ///
    /// If you want to write the element, you \b must make sure to capture
    /// a reference to the value. Otherwise you might accidentally copy
    /// it - writes to a copy have no effect on the model!
    ///
    /// Writing to a BlockParameter of type double will looks like this:
    /// \code{.cpp}
    /// db::simulink::BlockParameters bp { ModelStruct };
    /// auto& Gain { bp.get<double>("Controller/Discrete-Time Integrator/gainval") };
    /// Gain = 23.35;
    /// \endcode
    ///
    /// It is also possible to not store the reference, but rather write
    /// directly to it. This is not recommended when repeatedly writing the
    /// element, due to increased lookup overhead.
    /// \code{.cpp}
    /// db::simulink::BlockParameters bp { ModelStruct };
    /// bp.get<double>("Controller/Discrete-Time Integrator/gainval") = 23.35;
    /// \endcode
    ///
    /// \throws std::runtime_error if a type mismatch is detected (only when
    /// type checking is enabled).
    /// \see ptr()
    /// \see opt()
    template <typename T>
    inline T& get(const std::string& Name);

    /// Returns a pointer to the element.
    ///
    /// Not very spectacular - it does what you expect.
    ///
    /// You can use it like this:
    /// \code{.cpp}
    /// db::simulink::BlockParameters bp { ModelStruct };
    /// auto GainPtr { bp.ptr<double>("Controller/Discrete-Time Integrator/gainval") };
    /// *GainPtr = 23.35;
    /// \endcode
    /// \throws std::runtime_error if a type mismatch is detected (only when
    /// type checking is enabled).
    /// \see get().
    /// \see opt()
    template <typename T>
    inline T* const ptr(const std::string& Name);

    /// Returns an `optional` that might contain a reference to the desired
    /// element.
    ///
    /// This does not throw an exception if the denoted element does not exist.
    /// In this case an empty `std::optional` will be returned. This must be
    /// explicitly checked by using `has_value()` (see example below).
    /// \code{.cpp}
    /// db::simulink::BlockParameters bp { ModelStruct };
    /// auto Opt { bp.opt<double>("Controller/Discrete-Time Integrator/gainval") };
    /// ASSERT(Opt.has_value());
    /// Opt->get() = 23.35;
    /// \endcode
    /// \see get()
    /// \see ptr()
    template <typename T>
    std::optional<std::reference_wrapper<T>> opt(const std::string& PathAndName);

    /// \internal
    template <typename T>
    T* FindInMMI(rtwCAPI_ModelMappingInfo& MMI, const std::string& PathAndName);
    /// \internal
    template <typename T>
    T* FindInStaticMMI(rtwCAPI_ModelMappingInfo& MMI, const std::string& PathAndName);

    void HandleError(CapiError Error);
    CapiError Error();

}; // end of class CapiAccessor.

template <typename WrappedElement, typename ModelStruct, bool ExceptionsEnabled>
CapiAccessor<WrappedElement, ModelStruct, ExceptionsEnabled>::CapiAccessor(ModelStruct& MS)
    : mMS(MS)
{
}

template <typename WrappedElement, typename ModelStruct, bool ExceptionsEnabled>
template <typename T>
T& CapiAccessor<WrappedElement, ModelStruct, ExceptionsEnabled>::get(const std::string& PathAndName)
{
    static_assert(ExceptionsEnabled, "CapiAccessor::get() is only available with Exceptions disabled.");
    return *ptr<T>(PathAndName);
}

template <typename WrappedElement, typename ModelStruct, bool ExceptionsEnabled>
template <typename T>
std::optional<std::reference_wrapper<T>> CapiAccessor<WrappedElement, ModelStruct, ExceptionsEnabled>::opt(const std::string& PathAndName)
{
    auto ptr { FindInMMI<T>(mMS.DataMapInfo.mmi, PathAndName) };
    std::optional<std::reference_wrapper<T>> Result;
    if (ptr)
    {
        Result = *ptr;
    }

    return Result;
}

template <typename WrappedElement, typename ModelStruct, bool ExceptionsEnabled>
template <typename T>
T* const CapiAccessor<WrappedElement, ModelStruct, ExceptionsEnabled>::ptr(const std::string& PathAndName)
{
    auto E { opt<T>(PathAndName) };
    if (!E.has_value())
    {
        std::ostringstream os;
        os << "Couldn't find Parameter '"
           << PathAndName << "'";
        CapiError Error { os.str(), ErrorType::NotFound };
        HandleError(Error);
        return nullptr;
    };
    return &E.value().get();
}

template <typename WrappedElement, typename ModelStruct, bool ExceptionsEnabled>
template <typename T>
T* CapiAccessor<WrappedElement, ModelStruct, ExceptionsEnabled>::FindInMMI(rtwCAPI_ModelMappingInfo& MMI, const std::string& PathAndName)
{
    auto Result { FindInStaticMMI<T>(MMI, PathAndName) };

    const std::size_t NumModels { MMI.InstanceMap.childMMIArrayLen };
    for (int i {}; Result == nullptr && i < NumModels; ++i)
    {
        Result = FindInMMI<T>(*MMI.InstanceMap.childMMIArray[i], PathAndName);
    }

    return Result;
}

template <typename WrappedElement, typename ModelStruct, bool ExceptionsEnabled>
template <typename T>
T* CapiAccessor<WrappedElement, ModelStruct, ExceptionsEnabled>::FindInStaticMMI(rtwCAPI_ModelMappingInfo& MMI, const std::string& PathAndName)
{
    T* Result { nullptr };

    const auto NumElements { db::simulink::GetCount<WrappedElement>(MMI) };
    const auto Data { db::simulink::GetRawData<WrappedElement>(MMI) };
    void* const* const AddrMap { rtwCAPI_GetDataAddressMap(&MMI) };

    // TODO: replace with std search algorithm
    for (std::size_t i {}; Result == nullptr && i < NumElements; ++i)
    {
        std::string CurrentParameter { db::simulink::GetName<WrappedElement>(MMI, i) };
        if (CurrentParameter == PathAndName)
        {
#ifdef ENABLE_RUNTIME_TYPE_CHECKING
            std::size_t DataTypeIndex { db::simulink::GetDataTypeIdx(Data, i) };
            auto DataTypeMap { db::simulink::GetRawData<rtwCAPI_DataTypeMap>(MMI) };
            std::string ActualType { db::simulink::GetTypeName<T>(DataTypeMap, DataTypeIndex) };
            std::string DeducedType { cleantype::clean<std::remove_reference_t<T>>() };

            if (ActualType != DeducedType)
            {
                std::ostringstream os;
                os << "Type mismatch "
                   << "(" << ActualType
                   << " vs. " << DeducedType;
                CapiError Error { os.str(), ErrorType::TypeMismatch };
                HandleError(Error);
            }
#endif
            const std::size_t AddrIndex { db::simulink::GetAddrIdx(Data, i) };
            Result = db::simulink::GetDataAddress<T>(AddrMap, AddrIndex);
        }
    }
    return Result;
}

template <typename WrappedElement, typename ModelStruct, bool ExceptionsEnabled>
void CapiAccessor<WrappedElement, ModelStruct, ExceptionsEnabled>::HandleError(CapiError Error)
{
    if constexpr (ExceptionsEnabled)
    {
        mError = Error;
        throw std::runtime_error(Error.Message);
    }
    else
    {
        mError = Error;
    }
}

template <typename WrappedElement, typename ModelStruct, bool ExceptionsEnabled>
CapiError CapiAccessor<WrappedElement, ModelStruct, ExceptionsEnabled>::Error()
{
    return mError;
}

}
#endif