// Simulink CAPI - C++ header only library to interface with code generated by Simulink.
// Copyright (C) 2020-2021  Danish Belal
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License Version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License along
// with this program; if not, write to the Free Software Foundation, Inc.,
// 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

#ifndef _PARAMETER_HPP_
#define _PARAMETER_HPP_

#include <exception>
#include <string>

#include "Accessor.hpp"
#include "join.hpp"
#include "split.hpp"

namespace db::simulink
{
class BlockParameters
{
    const std::size_t mNumParams;
    const rtwCAPI_BlockParameters* const mBP;
    void* const* const mAddrMap;

public:
    using WrappedElement = rtwCAPI_BlockParameters;
    BlockParameters(const rtwCAPI_ModelMappingInfo& MMI);

    // Returns a reference to the Parameter.
    template <typename T>
    inline T& get(const std::string Name);
    template <typename T>
    inline T& get(const std::string& BlockPath, const std::string& Name);
}; // end of class BlockParameters

BlockParameters::BlockParameters(const rtwCAPI_ModelMappingInfo& MMI)
    : mNumParams(db::simulink::GetCount<WrappedElement>(MMI))
    , mBP(db::simulink::GetRawData<WrappedElement>(MMI))
    , mAddrMap(rtwCAPI_GetDataAddressMap(&MMI))
{
}

template <typename T>
T& BlockParameters::get(const std::string PathAndName)
{
    auto PathElems = db::utils::split(PathAndName, '/');
    if (PathElems.size() < 2)
    {
        throw std::runtime_error("Invalid path");
    }
    std::string Name = PathElems.back();
    PathElems.pop_back();

    auto Path = db::utils::join(PathElems, '/');

    return get<T>(Path, Name);
}

template <typename T>
T& BlockParameters::get(const std::string& BlockPath, const std::string& Name)
{
    // Search for the Parameter given its Block Path and Name.
    for (std::size_t i { 0 }; i < mNumParams; ++i)
    {
        std::string CurrentParameter { db::simulink::GetName(mBP, i) };
        std::string CurrentPath { db::simulink::GetBlockPath(mBP, i) };
        if ((CurrentParameter == Name) && (CurrentPath == BlockPath))
        {
            const std::size_t AddrIndex { db::simulink::GetAddrIdx(mBP, i) };
            return *db::simulink::GetDataAddress<T>(mAddrMap, AddrIndex);
        }
    }
    throw std::runtime_error("Couldn't find Parameter");
}
}
#endif